## Defines base image
#FROM openjdk:25-ea-21-slim-bullseye
#
## Information around who maintains the image
#LABEL "org.opencontainers.image.authors"="leomanzini"
#
## Copy fat jar to the image
#COPY target/accounts-0.0.1-SNAPSHOT.jar accounts.jar
#
## How the container will run when started
#ENTRYPOINT ["java", "-jar", "/accounts.jar"]