services:
  accounts:
    image: "manzini/accounts:0.0.1"
    container_name: "accounts-ms"
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - manzini
  loans:
    image: "manzini/loans:0.0.1-SNAPSHOT"
    container_name: "loans-ms"
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - manzini
  cards:
    image: "manzini/cards:0.0.1-SNAPSHOT"
    container_name: "cards-ms"
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - manzini
networks:
  manzini:
    driver: "bridge"