server:
  port: 8090
spring:
  application:
    name: loans
  # H2 configuration
  datasource:
    url: jdbc:h2:mem:cards
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  # JPA configuration
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        ddl:
          auto: update
build:
  version: "0.0.1-SNAPSHOT"
loans:
  message: "Hello from loans service"
  contactDetails:
    name: "John Doe - Loans Service"
    email: "john-doe@mail.com"
  onCallSupport:
    - (555) 555-5555
    - (555) 555-5556