build:
  version: "1.3.0"
cards:
  message: "Hello from cards production service"
  contactDetails:
    name: "John Doe - Cards Prod Service"
    email: "john-doe@mail.com"
  onCallSupport:
    - (555) 555-5555
    - (555) 555-5556