build:
  version: "1.3.50"
cards:
  message: "Hello from cards qa service"
  contactDetails:
    name: "John Doe - Cards QA Service"
    email: "john-doe@mail.com"
  onCallSupport:
    - (555) 555-5555
    - (555) 555-5556