build:
  version: "0.0.0"
loans:
  message: "Hello from loans qa service"
  contactDetails:
    name: "John Doe - Loans QA Service"
    email: "john-doe@mail.com"
  onCallSupport:
    - (555) 555-5555
    - (555) 555-5556