server:
  port: 8080
spring:
  application:
    name: accounts
# H2 configuration
  datasource:
    url: jdbc:h2:mem:accounts
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
# JPA configuration
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        ddl:
          auto: update
  config:
    import: "optional:configserver:http://localhost:8071/"
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"
  cloud:
    bus:
      enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"