CREATE TABLE IF NOT EXISTS CUSTOMER (
    CUSTOMER_ID int AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    MOBILE_NUMBER VARCHAR(20) NOT NULL,
    CREATED_AT DATE NOT NULL,
    CREATED_BY VARCHAR(20) NOT NULL,
    UPDATED_AT DATE DEFAULT NULL,
    UPDATED_BY VARCHAR(20) DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS ACCOUNTS (
    ACCOUNT_NUMBER INT AUTO_INCREMENT PRIMARY KEY,
    CUSTOMER_ID INT NOT NULL,
    ACCOUNT_TYPE VARCHAR(100) NOT NULL,
    BRANCH_ADDRESS VARCHAR(200) NOT NULL,
    CREATED_AT DATE NOT NULL,
    CREATED_BY VARCHAR(20) NOT NULL,
    UPDATED_AT DATE DEFAULT NULL,
    UPDATED_BY VARCHAR(20) DEFAULT NULL
);