services:
  configserver:
    image: "manzini/configserver:0.0.1-SNAPSHOT"
    container_name: "configserver-ms"
    ports:
      - "8071:8071"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - manzini
  accounts:
    image: "manzini/accounts:0.0.1-SNAPSHOT"
    container_name: "accounts-ms"
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - manzini
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_APPLICATION_NAME: "accounts"
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
  loans:
    image: "manzini/loans:0.0.1-SNAPSHOT"
    container_name: "loans-ms"
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - manzini
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_APPLICATION_NAME: "loans"
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
  cards:
    image: "manzini/cards:0.0.1-SNAPSHOT"
    container_name: "cards-ms"
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - manzini
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_APPLICATION_NAME: "cards"
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
networks:
  manzini:
    driver: "bridge"